const ActionTypes = {
  SET_CARS: 'SET_CARS',
  SET_RESERVATIONS: 'SET_RESERVATIONS',
  SELECTED_CAR: 'SELECTED_CAR',
  SELECTED_RESERVATION: 'SELECTED_RESERVATION',
  REMOVE_SELECTED_CAR: 'REMOVE_SELECTED_CAR',
};

export default ActionTypes;
